name: CI/CD - Build and Deploy to Cloud Run

on:
  push:
    branches:
      - main

env:
  PROJECT_ID: customer-churn-mlops-475818
  REGION: asia-south1
  SERVICE: telecom-churn-app
  REPO: my-ml-repo
  IMAGE: asia-south1-docker.pkg.dev/customer-churn-mlops-475818/my-ml-repo/my-ml-app

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up gcloud CLI
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ env.PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - name: Configure Docker authentication
        run: gcloud auth configure-docker ${{ env.REGION }}-docker.pkg.dev --quiet

      - name: Build Docker image
        run: docker build -t ${{ env.IMAGE }} .

      - name: Push Docker image to Artifact Registry
        run: docker push ${{ env.IMAGE }}

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy ${{ env.SERVICE }} \
            --image=${{ env.IMAGE }} \
            --region=${{ env.REGION }} \
            --platform=managed \
            --allow-unauthenticated
